### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by yangdaowu** [RobinWitch/SynTalker#4]
Hello, thank you for your great project. Could you please provide the code for data processing.

**Comment by RobinWitch** [comment]
Of course yes.
The data processing code is always along with our dataloader code such as [dataloaders/beat_sep_lower.py](https://github.com/RobinWitch/SynTalker/blob/6d0a67794040679eba06df9cabfad9ed7f4aa9be/dataloaders/beat_sep_lower.py#L224).
This process function will automatically run if you don't have a cache file. (You need to download the raw beat datasets following [download dataset](https://github.com/RobinWitch/SynTalker/tree/main?tab=readme-ov-file#download-dataset))

**Comment by yangdaowu** [comment]
Okay, thank you. I will close this issue.
